// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import DragController from "./drag_controller.js"
application.register("drag", DragController)

import NotificationMessageController from "./notification_message_controller.js"
application.register("notification-message", NotificationMessageController)
