// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application";

import NotificationMessageController from "./notification_message_controller.js";
application.register("notification_message", NotificationMessageController);
